import { NextResponse } from 'next/server'

import { logger } from '@/lib/logger'
import { prisma } from '@/modules/database'
import { ProcurementService } from '@/modules/procurement'

const procurementService = new ProcurementService()

export async function getRestockRequestDetail(id: string) {
  try {
    const pr = await prisma.purchaseRequest.findUnique({
      where: { id },
      include: {
        requester: { select: { name: true, email: true } },
        gudang: { select: { nama: true, kode: true } },
        items: {
          include: {
            barang: { select: { nama: true, kode: true, satuan: true } },
          },
        },
        purchaseOrder: { select: { id: true, poNumber: true, status: true } },
      },
    })

    if (!pr) {
      return NextResponse.json({ error: 'Purchase Request not found' }, { status: 404 })
    }

    return NextResponse.json(pr)
  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : 'Terjadi kesalahan server'
    console.error('Error fetching purchase request:', error)
    return NextResponse.json({ error: errorMessage }, { status: 500 })
  }
}

interface RestockRequestLifecycleInput {
  id: string
  action: unknown
  catatan: string | null | undefined
  actorId: string
}

export async function patchRestockRequestLifecycle({
  id,
  action,
  catatan,
  actorId,
}: RestockRequestLifecycleInput) {
  const startTime = Date.now()

  try {
    if (!['APPROVE', 'REJECT'].includes(String(action))) {
      return NextResponse.json({ error: 'Aksi tidak valid. Harus APPROVE atau REJECT' }, { status: 400 })
    }

    const normalizedAction = String(action) as 'APPROVE' | 'REJECT'

    const existing = await prisma.purchaseRequest.findUnique({
      where: { id },
      include: {
        items: {
          include: {
            barang: { select: { id: true, nama: true, supplierId: true } },
          },
        },
      },
    })

    if (!existing) {
      return NextResponse.json({ error: 'Purchase Request not found' }, { status: 404 })
    }

    if (existing.status !== 'DRAFT') {
      return NextResponse.json(
        { error: `Cannot ${normalizedAction.toLowerCase()} PR with status ${existing.status}` },
        { status: 400 }
      )
    }

    if (normalizedAction === 'REJECT') {
      const updated = await prisma.purchaseRequest.update({
        where: { id },
        data: {
          status: 'REJECTED',
          catatanApproval: catatan || null,
          approvedAt: new Date(),
          approvedBy: actorId,
        },
        include: {
          requester: { select: { name: true } },
          gudang: { select: { nama: true } },
        },
      })

      await logger.logActivity({
        userId: actorId,
        action: 'REJECT PurchaseRequest',
        subject: existing.nomorRequest,
        details: {
          id,
          previousStatus: existing.status,
          newStatus: 'REJECTED',
          catatan,
        },
      })

      return NextResponse.json(updated)
    }

    await prisma.purchaseRequest.update({
      where: { id },
      data: {
        status: 'APPROVED',
        catatanApproval: catatan || null,
        approvedAt: new Date(),
        approvedBy: actorId,
      },
    })

    let generatedPO = null
    let poError: string | null = null

    try {
      const pos = await procurementService.generatePOFromPRs([id], actorId)
      if (pos && pos.length > 0) {
        generatedPO = pos[0]
      }
    } catch (error: unknown) {
      poError = error instanceof Error ? error.message : 'Gagal auto-generate PO'
      console.error('Auto-generate PO error:', error)
    }

    await logger.logActivity({
      userId: actorId,
      action: 'APPROVE PurchaseRequest',
      subject: existing.nomorRequest,
      details: {
        id,
        previousStatus: existing.status,
        newStatus: generatedPO ? 'ORDERED' : 'APPROVED',
        catatan,
        generatedPO: generatedPO?.poNumber || null,
        poError,
      },
    })

    logger.apiRequest('PATCH', `/api/inventory/restock/requests/${id}`, 200, Date.now() - startTime, {
      userId: actorId,
      action: normalizedAction,
      generatedPO: generatedPO?.poNumber,
    })

    const updated = await prisma.purchaseRequest.findUnique({
      where: { id },
      include: {
        requester: { select: { name: true } },
        gudang: { select: { nama: true } },
        purchaseOrder: { select: { id: true, poNumber: true, status: true } },
      },
    })

    return NextResponse.json({
      ...updated,
      _autoGeneratedPO: generatedPO
        ? {
            id: generatedPO.id,
            poNumber: generatedPO.poNumber,
          }
        : null,
      _poError: poError,
    })
  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : 'Terjadi kesalahan server'
    logger.error('Error updating purchase request', error instanceof Error ? error : new Error(errorMessage), {
      path: '/api/inventory/restock/requests/[id]',
      method: 'PATCH',
    })
    return NextResponse.json({ error: errorMessage }, { status: 500 })
  }
}
