export const BYTES_PER_MB = 1048576;
export const BYTES_PER_GB = 1073741824;
export const PERCENT_PRECISION = 100;
export const DEFAULT_GROUP_PRIORITY = 0;
export const PACKAGE_GROUP_PRIORITY = 10;
export const ISOLIR_GROUP_PRIORITY = 1;
export const DEFAULT_SESSION_PAGE = 1;
export const DEFAULT_SESSION_LIMIT = 20;
export const DEFAULT_RECENT_SESSION_LIMIT = 50;
export const ACTIVE_STATUS = "active" as const;
export const MIKROTIK_RATE_LIMIT_ATTRIBUTE = "Mikrotik-Rate-Limit";
export const MIKROTIK_GROUP_ATTRIBUTE = "Mikrotik-Group";
export const FRAMED_POOL_ATTRIBUTE = "Framed-Pool";
export const POOL_NAME_ATTRIBUTE = "Pool-Name";
export const CLEAR_TEXT_PASSWORD_ATTRIBUTE = "Cleartext-Password";
export const EXPIRED_USERS_PROFILE = "expired users";
export const GROUP_REPLY_ASSIGN_OP = ":=";
export const GROUP_CHECK_MATCH_OP = "==";
export const ONE_SECOND_IN_MS = 1000;
export const ONE_HOUR_IN_SECONDS = 3600;
