export const AVAILABLE_WORK_ORDER_STATUS = "PENDING";
export const CLAIMED_WORK_ORDER_STATUS = "ASSIGNED";
export const MOBILE_AVAILABLE_WORK_ORDER_LIMIT = 50;
export const MOBILE_CLAIM_ROLE = "TEKNISI";
