-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastVersionCode" INTEGER;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastVersionName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastVersionUpdate" TIMESTAMP(3);
