'use client'

import { useState, useEffect, useCallback } from 'react'
import { HiCheck, HiX, HiEye, HiRefresh, HiSearch } from 'react-icons/hi'
import { Button } from '@/components/ui/Button'
import ResponsiveTable, { type Column } from '@/components/ui/ResponsiveTable'
import { Modal } from '@/components/ui/Modal'
import { usePermission } from '@/hooks/use-permission'
import toast from 'react-hot-toast'

interface PurchaseRequestItem {
    id: string
    jumlah: number
    hargaPerUnit: number
    barang: {
        nama: string
        kode: string
        satuan: string
    }
}

interface PurchaseRequest {
    id: string
    nomorRequest: string
    tanggal: string
    status: string
    prioritas: string
    keterangan?: string
    catatanApproval?: string
    requester: { name: string }
    gudang: { nama: string; kode: string }
    items: PurchaseRequestItem[]
    purchaseOrder?: { poNumber: string } | null
}

export default function PurchaseRequestTab() {
    const { hasPermission: can } = usePermission()
    const canUpdate = can('purchase_orders:update')

    const [data, setData] = useState<PurchaseRequest[]>([])
    const [loading, setLoading] = useState(true)
    const [search, setSearch] = useState('')
    const [debouncedSearch, setDebouncedSearch] = useState('')
    const [statusFilter, setStatusFilter] = useState('ALL')
    const [page, setPage] = useState(1)
    const [total, setTotal] = useState(0)
    const limit = 10

    // Modal states
    const [selectedPR, setSelectedPR] = useState<PurchaseRequest | null>(null)
    const [showDetail, setShowDetail] = useState(false)
    const [showApproveModal, setShowApproveModal] = useState(false)
    const [showRejectModal, setShowRejectModal] = useState(false)
    const [catatan, setCatatan] = useState('')
    const [processing, setProcessing] = useState(false)

    // Expanded rows for mobile
    const [_expandedRows, _setExpandedRows] = useState<Set<string>>(new Set())

    const fetchData = useCallback(async () => {
        setLoading(true)
        try {
            const skip = (page - 1) * limit
            const params = new URLSearchParams({
                skip: skip.toString(),
                take: limit.toString(),
                ...(debouncedSearch && { search: debouncedSearch }),
                ...(statusFilter !== 'ALL' && { status: statusFilter })
            })

            const res = await fetch(`/api/procurement/purchase-requests?${params}`)
            if (!res.ok) throw new Error('Failed to fetch')

            const json = await res.json()
            setData(json.data || [])
            setTotal(json.total || 0)
        } catch (error) {
            console.error(error)
            toast.error('Gagal mengambil data Purchase Request')
        } finally {
            setLoading(false)
        }
    }, [page, limit, debouncedSearch, statusFilter])

    useEffect(() => {
        const timer = setTimeout(() => setDebouncedSearch(search), 500)
        return () => clearTimeout(timer)
    }, [search])

    useEffect(() => {
        fetchData()
    }, [fetchData])

    const handleAction = async (action: 'APPROVE' | 'REJECT') => {
        if (!selectedPR) return
        setProcessing(true)

        try {
            const res = await fetch(`/api/procurement/purchase-requests/${selectedPR.id}`, {
                method: 'PATCH',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ action, catatan })
            })

            const json = await res.json()

            if (!res.ok) {
                throw new Error(json.error || 'Gagal')
            }

            if (action === 'APPROVE') {
                if (json._autoGeneratedPO) {
                    toast.success(`✅ PR di-approve dan PO berhasil dibuat: ${json._autoGeneratedPO.poNumber}`)
                } else if (json._poError) {
                    toast.success(`⚠️ PR di-approve. ${json._poError}`, { duration: 6000 })
                } else {
                    toast.success('Purchase Request berhasil di-approve')
                }
            } else {
                toast.success('Purchase Request berhasil di-reject')
            }

            setShowApproveModal(false)
            setShowRejectModal(false)
            setSelectedPR(null)
            setCatatan('')
            fetchData()
        } catch (error) {
            console.error(error)
            if (error instanceof Error) {
                toast.error(error.message)
            } else {
                toast.error('Gagal memproses Purchase Request')
            }
        } finally {
            setProcessing(false)
        }
    }

    const getStatusColor = (status: string) => {
        switch (status) {
            case 'DRAFT': return 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300'
            case 'APPROVED': return 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300'
            case 'REJECTED': return 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300'
            case 'ORDERED': return 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300'
            default: return 'bg-gray-100 text-gray-800'
        }
    }

    const getPriorityColor = (priority: string) => {
        return priority === 'URGENT'
            ? 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300'
            : 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300'
    }

    const columns: Column<PurchaseRequest>[] = [
        {
            header: 'No. Request',
            key: 'nomorRequest',
            priority: 'primary',
            render: (row) => (
                <div className="flex flex-col">
                    <span className="font-medium text-indigo-600 dark:text-indigo-400">{row.nomorRequest}</span>
                    <span className="text-xs text-gray-500">{new Date(row.tanggal).toLocaleDateString('id-ID')}</span>
                </div>
            )
        },
        {
            header: 'Gudang',
            key: 'gudang.nama',
            priority: 'secondary',
            render: (row) => (
                <div className="flex flex-col">
                    <span className="font-medium">{row.gudang?.kode}</span>
                    <span className="text-xs text-gray-500">{row.gudang?.nama}</span>
                </div>
            )
        },
        {
            header: 'Requester',
            key: 'requester.name',
            priority: 'secondary',
            render: (row) => row.requester?.name || '-'
        },
        {
            header: 'Items',
            key: 'items',
            priority: 'secondary',
            render: (row) => (
                <span className="text-sm">{row.items?.length || 0} Barang</span>
            )
        },
        {
            header: 'Status',
            key: 'status',
            priority: 'primary',
            render: (row) => (
                <div className="flex flex-col gap-1">
                    <span className={`inline-flex px-2 py-0.5 text-xs font-medium rounded-full ${getStatusColor(row.status)}`}>
                        {row.status}
                    </span>
                    <span className={`inline-flex px-2 py-0.5 text-xs font-medium rounded-full ${getPriorityColor(row.prioritas)}`}>
                        {row.prioritas}
                    </span>
                </div>
            )
        },
        {
            header: 'PO',
            key: 'purchaseOrder',
            priority: 'secondary',
            render: (row) => row.purchaseOrder?.poNumber || '-'
        },
        {
            header: 'Aksi',
            key: 'id',
            priority: 'primary',
            render: (row) => (
                <div className="flex gap-1">
                    <Button
                        onClick={() => { setSelectedPR(row); setShowDetail(true) }}
                        className="p-1.5 text-gray-500 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg"
                        title="Detail"
                    >
                        <HiEye className="w-5 h-5" />
                    </Button>
                    {canUpdate && row.status === 'DRAFT' && (
                        <>
                            <Button
                                onClick={() => { setSelectedPR(row); setShowApproveModal(true) }}
                                className="p-1.5 text-green-600 hover:bg-green-50 rounded-lg"
                                title="Approve"
                            >
                                <HiCheck className="w-5 h-5" />
                            </Button>
                            <Button
                                onClick={() => { setSelectedPR(row); setShowRejectModal(true) }}
                                className="p-1.5 text-red-600 hover:bg-red-50 rounded-lg"
                                title="Reject"
                            >
                                <HiX className="w-5 h-5" />
                            </Button>
                        </>
                    )}
                </div>
            )
        }
    ]

    const totalPages = Math.ceil(total / limit)

    return (
        <div className="space-y-4">
            {/* Filters */}
            <div className="flex flex-col sm:flex-row gap-3">
                <div className="relative flex-1">
                    <HiSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 w-5 h-5" />
                    <input
                        type="text"
                        placeholder="Cari No. Request..."
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        className="w-full pl-10 pr-4 py-2 rounded-lg border border-gray-200 dark:border-gray-600 bg-gray-50 dark:bg-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                    />
                </div>
                <select
                    value={statusFilter}
                    onChange={(e) => setStatusFilter(e.target.value)}
                    className="px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-600 bg-gray-50 dark:bg-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                >
                    <option value="ALL">Semua Status</option>
                    <option value="DRAFT">Draft</option>
                    <option value="APPROVED">Approved</option>
                    <option value="REJECTED">Rejected</option>
                    <option value="ORDERED">Ordered</option>
                </select>
                <Button variant="secondary"
                    onClick={fetchData}
                    
                >
                    <HiRefresh className="w-5 h-5" />
                </Button>
            </div>

            {/* Table */}
            <ResponsiveTable
                data={data}
                columns={columns}
                loading={loading}
                keyField="id"
                emptyMessage="Tidak ada Purchase Request"
            />

            {/* Pagination */}
            {total > 0 && (
                <div className="flex justify-between items-center pt-4 border-t border-gray-100 dark:border-gray-700">
                    <span className="text-sm text-gray-600 dark:text-gray-400">
                        Halaman {page} dari {totalPages} ({total} Data)
                    </span>
                    <div className="flex gap-2">
                        <Button
                            disabled={page === 1}
                            onClick={() => setPage(p => p - 1)}
                            className="px-3 py-1 text-sm border rounded-lg hover:bg-gray-50 disabled:opacity-50 dark:border-gray-600"
                        >
                            Prev
                        </Button>
                        <Button
                            disabled={page >= totalPages}
                            onClick={() => setPage(p => p + 1)}
                            className="px-3 py-1 text-sm border rounded-lg hover:bg-gray-50 disabled:opacity-50 dark:border-gray-600"
                        >
                            Next
                        </Button>
                    </div>
                </div>
            )}

            {/* Detail Modal */}
            <Modal
                isOpen={showDetail}
                onClose={() => { setShowDetail(false); setSelectedPR(null) }}
                title={`Detail PR: ${selectedPR?.nomorRequest}`}
                size="lg"
            >
                {selectedPR && (
                    <div className="space-y-4">
                        <div className="grid grid-cols-2 gap-4 text-sm">
                            <div>
                                <p className="text-gray-500">Tanggal</p>
                                <p className="font-medium">{new Date(selectedPR.tanggal).toLocaleDateString('id-ID')}</p>
                            </div>
                            <div>
                                <p className="text-gray-500">Requester</p>
                                <p className="font-medium">{selectedPR.requester?.name}</p>
                            </div>
                            <div>
                                <p className="text-gray-500">Gudang</p>
                                <p className="font-medium">{selectedPR.gudang?.kode} - {selectedPR.gudang?.nama}</p>
                            </div>
                            <div>
                                <p className="text-gray-500">Status</p>
                                <span className={`inline-flex px-2 py-0.5 text-xs font-medium rounded-full ${getStatusColor(selectedPR.status)}`}>
                                    {selectedPR.status}
                                </span>
                            </div>
                        </div>

                        {selectedPR.keterangan && (
                            <div>
                                <p className="text-sm text-gray-500">Keterangan</p>
                                <p className="text-sm">{selectedPR.keterangan}</p>
                            </div>
                        )}

                        <div>
                            <p className="text-sm font-medium mb-2">Items ({selectedPR.items?.length})</p>
                            <div className="border rounded-lg overflow-hidden">
                                <table className="w-full text-sm">
                                    <thead className="bg-gray-50 dark:bg-gray-700">
                                        <tr>
                                            <th className="px-3 py-2 text-left">Barang</th>
                                            <th className="px-3 py-2 text-right">Jumlah</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y">
                                        {selectedPR.items?.map((item) => (
                                            <tr key={item.id}>
                                                <td className="px-3 py-2">
                                                    <div>{item.barang?.kode}</div>
                                                    <div className="text-xs text-gray-500">{item.barang?.nama}</div>
                                                </td>
                                                <td className="px-3 py-2 text-right">
                                                    {item.jumlah} {item.barang?.satuan}
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        {selectedPR.catatanApproval && (
                            <div className="p-3 bg-gray-50 dark:bg-gray-700 rounded-lg">
                                <p className="text-sm text-gray-500">Catatan Approval</p>
                                <p className="text-sm">{selectedPR.catatanApproval}</p>
                            </div>
                        )}
                    </div>
                )}
            </Modal>

            {/* Approve Modal */}
            <Modal
                isOpen={showApproveModal}
                onClose={() => { setShowApproveModal(false); setCatatan('') }}
                title="Approve Purchase Request"
                size="sm"
            >
                <div className="space-y-4">
                    <p>Approve PR <strong>{selectedPR?.nomorRequest}</strong>?</p>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                            Catatan (Opsional)
                        </label>
                        <textarea
                            value={catatan}
                            onChange={(e) => setCatatan(e.target.value)}
                            className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600"
                            rows={3}
                            placeholder="Tambahkan catatan..."
                        />
                    </div>
                    <div className="flex justify-end gap-2">
                        <Button
                            onClick={() => { setShowApproveModal(false); setCatatan('') }}
                            className="px-4 py-2 text-gray-600 border rounded-lg hover:bg-gray-50"
                            disabled={processing}
                        >
                            Batal
                        </Button>
                        <Button
                            onClick={() => handleAction('APPROVE')}
                            className="px-4 py-2 text-white bg-green-600 rounded-lg hover:bg-green-700 disabled:opacity-50"
                            disabled={processing}
                        >
                            {processing ? 'Processing...' : 'Approve'}
                        </Button>
                    </div>
                </div>
            </Modal>

            {/* Reject Modal */}
            <Modal
                isOpen={showRejectModal}
                onClose={() => { setShowRejectModal(false); setCatatan('') }}
                title="Reject Purchase Request"
                size="sm"
            >
                <div className="space-y-4">
                    <p>Reject PR <strong>{selectedPR?.nomorRequest}</strong>?</p>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                            Alasan Reject <span className="text-red-500">*</span>
                        </label>
                        <textarea
                            value={catatan}
                            onChange={(e) => setCatatan(e.target.value)}
                            className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600"
                            rows={3}
                            placeholder="Masukkan alasan reject..."
                            required
                        />
                    </div>
                    <div className="flex justify-end gap-2">
                        <Button
                            onClick={() => { setShowRejectModal(false); setCatatan('') }}
                            className="px-4 py-2 text-gray-600 border rounded-lg hover:bg-gray-50"
                            disabled={processing}
                        >
                            Batal
                        </Button>
                        <Button
                            onClick={() => handleAction('REJECT')}
                            className="px-4 py-2 text-white bg-red-600 rounded-lg hover:bg-red-700 disabled:opacity-50"
                            disabled={processing || !catatan.trim()}
                        >
                            {processing ? 'Processing...' : 'Reject'}
                        </Button>
                    </div>
                </div>
            </Modal>
        </div>
    )
}
