apiVersion: v1
kind: ConfigMap
metadata:
  name: netmanager-config
  namespace: netmanager-staging
data:
  DOMAIN: "staging.radpro.id"
  AUTH_URL: "https://staging.radpro.id"
  NEXTAUTH_URL: "https://staging.radpro.id"
  TZ: "Asia/Jakarta"
  NODE_ENV: "production"
  DATABASE_URL_BILLING: "postgresql://netmgr:PASSWORD@db-billing:5432/billing?schema=public&connection_limit=20&pool_timeout=10"
  DATABASE_URL_MITRA: "postgresql://netmgr:PASSWORD@db-mitra:5432/mitra?schema=public&connection_limit=20&pool_timeout=10"
