apiVersion: v1
kind: ConfigMap
metadata:
  name: netmanager-config
  namespace: netmanager-staging
data:
  DOMAIN: "staging.radpro.id"
  AUTH_URL: "https://staging.radpro.id"
  NEXTAUTH_URL: "https://staging.radpro.id"
  TZ: "Asia/Jakarta"
  NODE_ENV: "production"
  ALLOWED_ORIGINS: "https://staging.radpro.id"
