apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: netmanager-staging
spec:
  type: ExternalName
  externalName: 141.11.160.150 # IP Publik Server Host
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: netmanager-staging
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - jenkins-staging.radpro.id
      secretName: jenkins-tls
  rules:
    - host: jenkins-staging.radpro.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins-service
                port:
                  number: 8080
