apiVersion: v1
kind: Secret
metadata:
  name: netmanager-secrets
  namespace: netmanager-staging
type: Opaque
# NOTE: Semua nilai harus dalam base64. Gunakan `echo -n 'nilai' | base64`
stringData:
  POSTGRES_PASSWORD: "netmanager_staging_db_pass"
  REDIS_PASSWORD: "netmanager_staging_redis_pass"
  RADIUS_SECRET: "netmanager_staging_radius_secret"
  AUTH_SECRET: "32_character_random_string_here"
  NEXTAUTH_SECRET: "32_character_random_string_here"
  OAUTH_ENCRYPTION_KEY: "64_character_hex_string_here"
  CRON_SECRET: "random_cron_secret_here"
  DATABASE_URL: "postgresql://netmgr:netmanager_staging_db_pass@db:5432/netmanager"
  RADIUS_DATABASE_URL: "postgresql://netmgr:netmanager_staging_db_pass@db-radius:5432/radius"
