-- Add missing values to RabItemCategory enum
ALTER TYPE "RabItemCategory" ADD VALUE IF NOT EXISTS 'DEVICE';
ALTER TYPE "RabItemCategory" ADD VALUE IF NOT EXISTS 'CABLE';
ALTER TYPE "RabItemCategory" ADD VALUE IF NOT EXISTS 'ACCESSORIES';
ALTER TYPE "RabItemCategory" ADD VALUE IF NOT EXISTS 'SERVICE';
ALTER TYPE "RabItemCategory" ADD VALUE IF NOT EXISTS 'OPERATIONAL';
