import { NextResponse } from "next/server";
import { logger } from "@/lib/logger";
import { prisma } from "@/modules/database";
import { ProcurementService } from "@/modules/procurement";

const procurementService = new ProcurementService();

type RestockAction = "APPROVE" | "REJECT" | "START_SHOPPING" | "RECEIVE";

interface RestockRequestLifecycleInput {
  id: string;
  action: unknown;
  catatan: string | null | undefined;
  actorId: string;
}

export class RestockRequestLifecycleService {
  /** Ubah lifecycle approval purchase request restock. */
  async patchRestockRequestLifecycle(input: RestockRequestLifecycleInput) {
    const startTime = Date.now();
    try {
      const normalizedAction = this.parseLifecycleAction(input.action);
      if (!normalizedAction) {
        return NextResponse.json(
          { error: "Aksi tidak valid. Harus APPROVE atau REJECT" },
          { status: 400 },
        );
      }
      const existingRequest = await this.getPurchaseRequestForLifecycle(
        input.id,
      );
      if (!existingRequest) {
        return NextResponse.json(
          { error: "Purchase Request not found" },
          { status: 404 },
        );
      }
      if (existingRequest.status !== "DRAFT") {
        return NextResponse.json(
          {
            error: `Cannot ${normalizedAction.toLowerCase()} PR with status ${existingRequest.status}`,
          },
          { status: 400 },
        );
      }
      if (normalizedAction === "REJECT") {
        return this.rejectPurchaseRequest(existingRequest, input);
      }
      return this.approvePurchaseRequest(existingRequest, input, startTime);
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : "Terjadi kesalahan server";
      logger.error(
        "Error updating purchase request",
        error instanceof Error ? error : new Error(errorMessage),
        { path: "/api/inventory/restock/requests/[id]", method: "PATCH" },
      );
      return NextResponse.json({ error: errorMessage }, { status: 500 });
    }
  }

  private parseLifecycleAction(action: unknown): RestockAction | null {
    if (action === "APPROVE" || action === "REJECT") return action;
    return null;
  }

  private getPurchaseRequestForLifecycle(id: string) {
    return prisma.purchaseRequest.findUnique({
      where: { id },
      include: {
        items: {
          include: {
            barang: { select: { id: true, nama: true, supplierId: true } },
          },
        },
      },
    });
  }

  private async rejectPurchaseRequest(
    existingRequest: NonNullable<
      Awaited<
        ReturnType<
          RestockRequestLifecycleService["getPurchaseRequestForLifecycle"]
        >
      >
    >,
    input: RestockRequestLifecycleInput,
  ) {
    const updatedRequest = await prisma.purchaseRequest.update({
      where: { id: input.id },
      data: {
        status: "REJECTED",
        catatanApproval: input.catatan || null,
        approvedAt: new Date(),
        approvedBy: input.actorId,
      },
      include: {
        requester: { select: { name: true } },
        gudang: { select: { nama: true } },
      },
    });
    await logger.logActivity({
      userId: input.actorId,
      action: "REJECT PurchaseRequest",
      subject: existingRequest.nomorRequest,
      details: {
        id: input.id,
        previousStatus: existingRequest.status,
        newStatus: "REJECTED",
        catatan: input.catatan,
      },
    });
    return NextResponse.json(updatedRequest);
  }

  private async approvePurchaseRequest(
    existingRequest: NonNullable<
      Awaited<
        ReturnType<
          RestockRequestLifecycleService["getPurchaseRequestForLifecycle"]
        >
      >
    >,
    input: RestockRequestLifecycleInput,
    startTime: number,
  ) {
    await prisma.purchaseRequest.update({
      where: { id: input.id },
      data: {
        status: "APPROVED",
        catatanApproval: input.catatan || null,
        approvedAt: new Date(),
        approvedBy: input.actorId,
      },
    });
    const generatedPurchaseOrder = await this.safelyGeneratePurchaseOrder(
      input.id,
      input.actorId,
    );
    await this.logApprovalActivity(
      existingRequest,
      input,
      generatedPurchaseOrder,
    );
    this.logApprovalRequest(input, startTime, generatedPurchaseOrder);
    const updatedRequest = await this.findApprovedRequest(input.id);
    return NextResponse.json({
      ...updatedRequest,
      _autoGeneratedPO: generatedPurchaseOrder.generatedPO
        ? {
            id: generatedPurchaseOrder.generatedPO.id,
            poNumber: generatedPurchaseOrder.generatedPO.poNumber,
          }
        : null,
      _poError: generatedPurchaseOrder.poError,
    });
  }

  private async safelyGeneratePurchaseOrder(
    id: string,
    actorId: string,
  ): Promise<{
    generatedPO:
      | Awaited<ReturnType<ProcurementService["generatePOFromPRs"]>>[number]
      | null;
    poError: string | null;
  }> {
    try {
      const generatedPurchaseOrders =
        await procurementService.generatePOFromPRs([id], actorId);
      return {
        generatedPO: generatedPurchaseOrders?.[0] ?? null,
        poError: null,
      };
    } catch (error: unknown) {
      return {
        generatedPO: null,
        poError:
          error instanceof Error ? error.message : "Gagal auto-generate PO",
      };
    }
  }

  private logApprovalActivity(
    existingRequest: NonNullable<
      Awaited<
        ReturnType<
          RestockRequestLifecycleService["getPurchaseRequestForLifecycle"]
        >
      >
    >,
    input: RestockRequestLifecycleInput,
    generatedPurchaseOrder: Awaited<
      ReturnType<RestockRequestLifecycleService["safelyGeneratePurchaseOrder"]>
    >,
  ) {
    return logger.logActivity({
      userId: input.actorId,
      action: "APPROVE PurchaseRequest",
      subject: existingRequest.nomorRequest,
      details: {
        id: input.id,
        previousStatus: existingRequest.status,
        newStatus: generatedPurchaseOrder.generatedPO ? "ORDERED" : "APPROVED",
        catatan: input.catatan,
        generatedPO: generatedPurchaseOrder.generatedPO?.poNumber || null,
        poError: generatedPurchaseOrder.poError,
      },
    });
  }

  private logApprovalRequest(
    input: RestockRequestLifecycleInput,
    startTime: number,
    generatedPurchaseOrder: Awaited<
      ReturnType<RestockRequestLifecycleService["safelyGeneratePurchaseOrder"]>
    >,
  ) {
    logger.apiRequest(
      "PATCH",
      `/api/inventory/restock/requests/${input.id}`,
      200,
      Date.now() - startTime,
      {
        userId: input.actorId,
        action: "APPROVE",
        generatedPO: generatedPurchaseOrder.generatedPO?.poNumber,
      },
    );
  }

  private findApprovedRequest(id: string) {
    return prisma.purchaseRequest.findUnique({
      where: { id },
      include: {
        requester: { select: { name: true } },
        gudang: { select: { nama: true } },
        purchaseOrder: { select: { id: true, poNumber: true, status: true } },
      },
    });
  }
}
