import { z } from 'zod'

export const oltCreateSchema = z.object({
  name: z.string().trim().min(1, 'Nama OLT wajib diisi'),
  ipAddress: z.string().trim().min(1, 'IP Address wajib diisi').regex(/^(\d{1,3}\.){3}\d{1,3}$/, 'Format IP Address tidak valid'),
  type: z.string().trim().min(1, 'Type OLT wajib diisi'),
  version: z.string().trim().optional().nullable(),
  temperature: z.number().int().optional().nullable(),
  connectedDevices: z.number().int().min(0).optional(),
  model: z.string().trim().optional().nullable(),
  uptime: z.string().trim().optional().nullable(),
  syncStatus: z.string().optional(),
  syncDate: z.string().optional().nullable(),
  telnetConnected: z.boolean().optional(),
  snmpConnected: z.boolean().optional(),
  snmpCommunityWrite: z.string().trim().optional(),
  snmpVersion: z.string().trim().optional(),
  snmpPort: z.number().int().min(1).max(65535).optional(),
  telnetUsername: z.string().trim().optional(),
  telnetPassword: z.string().min(1, 'Password Telnet wajib diisi'),
  telnetPort: z.number().int().min(1).max(65535).optional(),
  siteId: z.string().optional(),
})

export const oltUpdateSchema = z.object({
  name: z.string().trim().min(1).optional(),
  ipAddress: z.string().trim().min(1).regex(/^(\d{1,3}\.){3}\d{1,3}$/, 'Format IP Address tidak valid').optional(),
  type: z.string().trim().min(1).optional(),
  version: z.string().trim().optional().nullable(),
  temperature: z.number().int().optional().nullable(),
  connectedDevices: z.number().int().min(0).optional(),
  model: z.string().trim().optional().nullable(),
  uptime: z.string().trim().optional().nullable(),
  syncStatus: z.string().optional(),
  syncDate: z.string().optional().nullable(),
  telnetConnected: z.boolean().optional(),
  snmpConnected: z.boolean().optional(),
  snmpCommunityWrite: z.string().trim().optional(),
  snmpVersion: z.string().trim().optional(),
  snmpPort: z.number().int().min(1).max(65535).optional(),
  telnetUsername: z.string().trim().optional(),
  telnetPassword: z.string().optional(),
  telnetPort: z.number().int().min(1).max(65535).optional(),
  siteId: z.string().optional(),
})

