import { z } from 'zod'

export const onuCreateSchema = z.object({
  oltId: z.string().min(1, 'OLT ID wajib diisi'),
  name: z.string().trim().min(1, 'Nama ONU wajib diisi'),
  description: z.string().trim().optional().nullable(),
  pppoe: z.string().trim().optional().nullable(),
  gponOnu: z.string().trim().min(1, 'GPON ONU wajib diisi'),
  status: z.string().trim().min(1, 'Status wajib diisi'),
  rxOlt: z.string().trim().optional().nullable(),
  rxOnu: z.string().trim().optional().nullable(),
  txOlt: z.string().trim().optional().nullable(),
  txOnu: z.string().trim().optional().nullable(),
  serialNumber: z.string().trim().optional().nullable(),
  actualType: z.string().trim().optional().nullable(),
  registerTime: z.string().optional().nullable(),
  distance: z.number().optional().nullable(),
  lastSeen: z.string().optional().nullable(),
  registrationMode: z.string().trim().optional().nullable(),
  softwareVersion: z.string().trim().optional().nullable(),
  hardwareVersion: z.string().trim().optional().nullable(),
  temperature: z.number().optional().nullable(),
  laserBiasCurrent: z.number().optional().nullable(),
  // New fields from ZTE-AN-PON-MIB
  vendorId: z.string().trim().optional().nullable(),
  equipmentId: z.string().trim().optional().nullable(),
  firmwareVersion: z.string().trim().optional().nullable(),
  macAddress: z.string().trim().optional().nullable(),
  batteryStatus: z.string().trim().optional().nullable(),
  opticalTransceiverType: z.string().trim().optional().nullable(),
  lastDeregTime: z.string().optional().nullable(),
  authMode: z.string().trim().optional().nullable(),
  loid: z.string().trim().optional().nullable(),
  password: z.string().trim().optional().nullable(),
  configState: z.string().trim().optional().nullable(),
  powerLevel: z.string().trim().optional().nullable(),
  dyingGaspTime: z.string().optional().nullable(),
  rxPowerStatus: z.string().trim().optional().nullable(),
  txPowerStatus: z.string().trim().optional().nullable(),
  // Performance Statistics
  rxBytes: z.number().optional().nullable(),
  txBytes: z.number().optional().nullable(),
  rxPackets: z.number().optional().nullable(),
  txPackets: z.number().optional().nullable(),
  rxErrors: z.number().optional().nullable(),
  txErrors: z.number().optional().nullable(),
  rxDrops: z.number().optional().nullable(),
  txDrops: z.number().optional().nullable(),
  // WiFi Configuration
  wifiEnable: z.boolean().optional().nullable(),
  wifiSsid: z.string().trim().optional().nullable(),
  wifiSecurityMode: z.string().trim().optional().nullable(),
  wifiChannel: z.number().int().optional().nullable(),
  // SNMP OID fields - untuk fast SNMP GET
  statusOid: z.string().trim().optional().nullable(),
  rxOltOid: z.string().trim().optional().nullable(),
  rxOnuOid: z.string().trim().optional().nullable(),
  nameOid: z.string().trim().optional().nullable(),
  descOid: z.string().trim().optional().nullable(),
  compositeIndex: z.number().int().optional().nullable(),
})

export const onuUpdateSchema = z.object({
  name: z.string().trim().min(1, 'Nama ONU wajib diisi').optional(),
  description: z.string().trim().optional().nullable(),
  pppoe: z.string().trim().optional().nullable(),
  status: z.string().trim().optional(),
  rxOlt: z.string().trim().optional().nullable(),
  rxOnu: z.string().trim().optional().nullable(),
  txOlt: z.string().trim().optional().nullable(),
  txOnu: z.string().trim().optional().nullable(),
  serialNumber: z.string().trim().optional().nullable(),
  actualType: z.string().trim().optional().nullable(),
  registerTime: z.string().optional().nullable(),
  distance: z.number().optional().nullable(),
  lastSeen: z.string().optional().nullable(),
  registrationMode: z.string().trim().optional().nullable(),
  softwareVersion: z.string().trim().optional().nullable(),
  hardwareVersion: z.string().trim().optional().nullable(),
  temperature: z.number().optional().nullable(),
  laserBiasCurrent: z.number().optional().nullable(),
  // New fields from ZTE-AN-PON-MIB
  vendorId: z.string().trim().optional().nullable(),
  equipmentId: z.string().trim().optional().nullable(),
  firmwareVersion: z.string().trim().optional().nullable(),
  macAddress: z.string().trim().optional().nullable(),
  batteryStatus: z.string().trim().optional().nullable(),
  opticalTransceiverType: z.string().trim().optional().nullable(),
  lastDeregTime: z.string().optional().nullable(),
  authMode: z.string().trim().optional().nullable(),
  loid: z.string().trim().optional().nullable(),
  password: z.string().trim().optional().nullable(),
  configState: z.string().trim().optional().nullable(),
  powerLevel: z.string().trim().optional().nullable(),
  dyingGaspTime: z.string().optional().nullable(),
  rxPowerStatus: z.string().trim().optional().nullable(),
  txPowerStatus: z.string().trim().optional().nullable(),
  // Performance Statistics
  rxBytes: z.number().optional().nullable(),
  txBytes: z.number().optional().nullable(),
  rxPackets: z.number().optional().nullable(),
  txPackets: z.number().optional().nullable(),
  rxErrors: z.number().optional().nullable(),
  txErrors: z.number().optional().nullable(),
  rxDrops: z.number().optional().nullable(),
  txDrops: z.number().optional().nullable(),
  // WiFi Configuration
  wifiEnable: z.boolean().optional().nullable(),
  wifiSsid: z.string().trim().optional().nullable(),
  wifiSecurityMode: z.string().trim().optional().nullable(),
  wifiChannel: z.number().int().optional().nullable(),
  lastUpdate: z.string().optional(),
})