import type { ElementType, ReactNode } from "react";
import {
  HiArrowRightOnRectangle,
  HiChevronDown,
  HiChevronRight,
  HiOutlineArchiveBox,
  HiOutlineArrowDownTray,
  HiOutlineArrowPath,
  HiOutlineArrowTrendingUp,
  HiOutlineArrowUpTray,
  HiOutlineArrowUturnLeft,
  HiOutlineArrowsRightLeft,
  HiOutlineBanknotes,
  HiOutlineBolt,
  HiOutlineBriefcase,
  HiOutlineBuildingLibrary,
  HiOutlineBuildingOffice,
  HiOutlineBuildingStorefront,
  HiOutlineCalendar,
  HiOutlineChartBar,
  HiOutlineChartPie,
  HiOutlineChatBubbleLeftRight,
  HiOutlineCircleStack,
  HiOutlineClipboard,
  HiOutlineClipboardDocumentCheck,
  HiOutlineClipboardDocumentList,
  HiOutlineClock,
  HiOutlineCloud,
  HiOutlineCodeBracket,
  HiOutlineCog6Tooth,
  HiOutlineComputerDesktop,
  HiOutlineCreditCard,
  HiOutlineCube,
  HiOutlineCurrencyDollar,
  HiOutlineDevicePhoneMobile,
  HiOutlineDocument,
  HiOutlineDocumentText,
  HiOutlineEnvelope,
  HiOutlineGlobeAlt,
  HiOutlineHome,
  HiOutlineInbox,
  HiOutlineKey,
  HiOutlineLink,
  HiOutlineMap,
  HiOutlineMapPin,
  HiOutlineMegaphone,
  HiOutlineNoSymbol,
  HiOutlinePhoto,
  HiOutlinePresentationChartBar,
  HiOutlinePresentationChartLine,
  HiOutlineQueueList,
  HiOutlineServer,
  HiOutlineServerStack,
  HiOutlineShieldCheck,
  HiOutlineShoppingBag,
  HiOutlineShoppingCart,
  HiOutlineSpeakerWave,
  HiOutlineSquares2X2,
  HiOutlineTag,
  HiOutlineTicket,
  HiOutlineTruck,
  HiOutlineUser,
  HiOutlineUserGroup,
  HiOutlineUsers,
  HiOutlineWifi,
  HiOutlineWrench,
  HiPlus,
  HiSparkles,
  HiXMark,
  HiOutlineCalculator,
  HiOutlineCalendarDays,
  HiOutlineListBullet,
  HiOutlineScale,
  HiOutlineAdjustmentsHorizontal,
  HiOutlineBellAlert,
  HiOutlineCpuChip,
  HiOutlineExclamationCircle,
  HiOutlineReceiptPercent,
} from "react-icons/hi2";

const adminSidebarIconMap: Record<string, ElementType> = {
  HiOutlineChartBar,
  HiOutlineGlobeAlt,
  HiOutlineServer,
  HiOutlineServerStack,
  HiOutlinePresentationChartLine,
  HiOutlineDevicePhoneMobile,
  HiPlus,
  HiOutlineClipboard,
  HiOutlineBolt,
  HiOutlineLink,
  HiOutlineHome,
  HiOutlineMap,
  HiOutlineUsers,
  HiChevronRight,
  HiChevronDown,
  HiOutlineWifi,
  HiOutlineCpuChip,
  HiOutlineArchiveBox,
  HiOutlineSquares2X2,
  HiOutlineQueueList,
  HiOutlineDocument,
  HiOutlineShoppingCart,
  HiOutlineCircleStack,
  HiOutlineUser,
  HiOutlineArrowTrendingUp,
  HiOutlineCreditCard,
  HiOutlineKey,
  HiOutlineCog6Tooth,
  HiOutlinePhoto,
  HiOutlineEnvelope,
  HiOutlineChatBubbleLeftRight,
  HiOutlineCodeBracket,
  HiOutlineClock,
  HiOutlineCalendar,
  HiOutlineUserGroup,
  HiOutlineWrench,
  HiOutlineCube,
  HiOutlineTruck,
  HiOutlineArrowDownTray,
  HiOutlineArrowUpTray,
  HiOutlineArrowUturnLeft,
  HiOutlineCurrencyDollar,
  HiXMark,
  HiArrowRightOnRectangle,
  HiSparkles,
  HiOutlineClipboardDocumentList,
  HiOutlineShieldCheck,
  HiOutlineDocumentText,
  HiOutlineMegaphone,
  HiOutlineBriefcase,
  HiOutlineBuildingOffice,
  HiOutlineBuildingStorefront,
  HiOutlineClipboardDocumentCheck,
  HiOutlineTag,
  HiOutlineTicket,
  HiOutlineMapPin,
  HiOutlineSpeakerWave,
  HiOutlineArrowPath,
  HiOutlineShoppingBag,
  HiOutlineBuildingLibrary,
  HiOutlineChartPie,
  HiOutlineComputerDesktop,
  HiOutlinePresentationChartBar,
  HiOutlineCloud,
  HiOutlineArrowsRightLeft,
  HiOutlineNoSymbol,
  HiOutlineBanknotes,
  HiOutlineCalculator,
  HiOutlineCalendarDays,
  HiOutlineListBullet,
  HiOutlineScale,
  HiOutlineAdjustmentsHorizontal,
  HiOutlineBellAlert,
  HiOutlineExclamationCircle,
  HiOutlineInbox,
  HiOutlineReceiptPercent,
};

/** Tujuan: merender ikon sidebar admin berdasarkan nama ikon konfigurasi. */
export function renderAdminSidebarIcon(
  name: string | undefined,
  className: string,
): ReactNode {
  if (!name || !adminSidebarIconMap[name]) {
    return null;
  }

  const Icon = adminSidebarIconMap[name];
  return <Icon className={className} />;
}

export { HiArrowRightOnRectangle, HiChevronDown, HiSparkles, HiXMark };
