apiVersion: v1
kind: ConfigMap
metadata:
  name: netmanager-config
  namespace: netmanager-production
data:
  DOMAIN: "radpro.id"
  AUTH_URL: "https://radpro.id"
  NEXTAUTH_URL: "https://radpro.id"
  NEXT_PUBLIC_APP_URL: "https://radpro.id"
  TZ: "Asia/Jakarta"
  NODE_ENV: "production"
  ALLOWED_ORIGINS: "https://radpro.id,https://admin.radpro.id,https://karyawan.radpro.id,https://pelanggan.radpro.id,https://investor.radpro.id"
  K8S_NAMESPACE: "netmanager-production"
