apiVersion: v1
kind: Secret
metadata:
  name: netmanager-production-registry
  namespace: netmanager-production
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"REGISTRY_URL":{"username":"REGISTRY_USERNAME","password":"REGISTRY_PASSWORD","auth":"REGISTRY_AUTH"}}}'
