ALTER TABLE "barang_masuk" ADD COLUMN IF NOT EXISTS "actorType" TEXT;
ALTER TABLE "barang_masuk" ADD COLUMN IF NOT EXISTS "actorId" TEXT;
ALTER TABLE "barang_keluar" ADD COLUMN IF NOT EXISTS "actorType" TEXT;
ALTER TABLE "barang_keluar" ADD COLUMN IF NOT EXISTS "actorId" TEXT;
